import type { ReactNode } from "react";
import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const year = new Date().getFullYear();

  return (
    <html lang="en">
      <body className="bg-slate-950 text-slate-100">
        <div className="flex min-h-screen flex-col">
          <header className="border-b border-slate-800 bg-gradient-to-r from-sky-600 via-blue-600 to-cyan-500 text-white shadow-lg">
            <div className="mx-auto flex h-16 w-full max-w-5xl items-center justify-between px-6">
              <Link href="/" className="text-lg font-semibold tracking-tight">
                Next.js Landing
              </Link>
              <nav className="flex items-center gap-6 text-sm text-white/90">
                <Link href="/" className="transition hover:scale-[1.02] hover:text-white">
                  Home
                </Link>
                <Link href="/products" className="transition hover:scale-[1.02] hover:text-white">
                  Products
                </Link>
              </nav>
            </div>
          </header>

          <main className="flex-1 bg-slate-950">
            {children}
          </main>

          <footer className="border-t border-slate-800 bg-slate-900/90">
            <div className="mx-auto w-full max-w-5xl px-6 py-8 text-sm text-slate-300">
              <p className="font-medium text-slate-200">
                &copy; {year} Next.js Landing. All rights reserved.
              </p>
              <p className="mt-2 text-xs text-slate-400">
                Crafted with Next.js and Tailwind CSS.
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
